### ISSUE TITLE
German 0.97 Sites: Faulty data

### ISSUE THREAD

**Issue by BathoryAtrahor** [lotgd/census#1]
The code doesn't seem to work with German 0.97 sites. :)

**Comment by austenmc** [comment]
Yeah I noticed. Will try to take a pass at a fix. :)

**Comment by austenmc** [comment]
I think this will be fixed for a few of the sites. I couldnt get the script to work for http://www.alvion-logd.de/logd/ b/c their HTML is too poorly formatted. Maybe Ill make another attempt later.

Leaving this open until the app runs once, just to make sure the data is valid.

**Comment by BathoryAtrahor** [comment]
Thx!
BTW:

str_replace('Gastern', '1 days', $t);

It should be:

str_replace('Gestern', '1 days', $t);

:)

**Comment by austenmc** [comment]
Thanks!
